application: raspi-temperature-01
version: 3 
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: index.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
